name: 爬取器

on:
  schedule:
    - cron: '9 * * * *'

  workflow_dispatch:
    inputs:
      dsa_http:
        default: ''
        description: 'DSA Con Server HTTP Host'
        type: string

      dsa_auth:
        description: 'DSA Auth '
        default: ''
        type: string

      dsa_config:
        description: '强制更新指定page, Config.name'
        type: string

      dsa_debug:
        description: 'DEBUG'
        type: string
        default: ''


jobs:
  downloader:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Chrome and ChromeDriver
        run: |-
          
          # Install Chrome
          echo 'Installing Chrome'
          wget "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb" \
            --progress=dot:giga -O /tmp/chrome.deb
          sudo apt-get install --allow-downgrades -y /tmp/chrome.deb
          rm /tmp/chrome.deb
          
          # Install ChromeDriver
          ENDPOINT='https://chromedriver.storage.googleapis.com'
          RELEASE="$(google-chrome --version | sed -E 's/.* ([0-9]+\.[0-9]+\.[0-9]+).*/\1/')"
          DRIVER_VERSION="$(wget --no-verbose -O - "${ENDPOINT}/LATEST_RELEASE_${RELEASE}")";
          echo "Installing ChromeDriver ${DRIVER_VERSION}"
          wget "${ENDPOINT}/${DRIVER_VERSION}/chromedriver_linux64.zip" \
            --progress=dot:giga -O /tmp/chromedriver.zip
          
          sudo rm -rf /opt/chromedriver
          sudo mkdir -p /opt/chromedriver
          sudo unzip /tmp/chromedriver.zip -d /opt/chromedriver
          sudo chmod +x /opt/chromedriver/chromedriver
          sudo ln -sf /opt/chromedriver/chromedriver /usr/local/bin/chromedriver
          rm /tmp/chromedriver.zip
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - name: main
        run: |-
          set +e
          echo Will spider all config.
          mkdir upload_log/
          times_in_while=0
          while true;do 
            ((times_in_while++))
            rm -rf logs/
            mkdir -p logs
            python __main__.py
            exit_code=$?

            name=$(cat last_config_name)
            mv logs upload_log/${name:-${times_in_while}}
            
            case $exit_code in 
            0 )
              echo ok, Next ... ;;
            119 )
              echo All Done . 
              exit 0
              ;;
            * ) 
              echo Find A Error in this Workers.;
              exit 1
              ;;
            esac
          done

          echo 
          echo "RunTimes $times_in_while ..."
        env:
          IN_DSA_HTTP: ${{ inputs.dsa_http }}
          IN_DSA_AUTH: ${{ inputs.dsa_auth }}
          ENV_DSA_HTTP: ${{ secrets.DSA_HTTP }}
          ENV_DSA_AUTH: ${{ secrets.DSA_AUTH }}
          DSA_CONFIG: ${{ inputs.dsa_config }}
          DSA_DEBUG: ${{ inputs.dsa_debug }}

      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: upload_log/